routes/web.php
<?php

use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use App\Mail\AdminReport;
use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function() {
    return redirect()->route('posts.index');
});


Route::resource('users', UserController::class);
Route::resource('posts', PostController::class);

Auth::routes();

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class Post extends Model
{
    use HasFactory;

    const PER_PAGE = 10;

    protected $fillable = ['title', 'content', 'user_id'];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class)->orderByDesc('id');
    }

    public function getDescriptionAttribute() {
        return Str::words(strip_tags($this->content), 25);
    }
}

app/Http/Controllers/Api/PostController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Post\CreatePostRequest;
use App\Http\Requests\Post\EditPostRequest;
use App\Http\Requests\Post\UpdatePostRequest;
use App\Http\Resources\PostResource;
use App\Services\Contracts\IPostService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{

    protected IPostService $postService;

    public function __construct(IPostService $postService)
    {
        $this->postService = $postService;
    }

    public function index()
    {
        $posts = $this->postService->getAll();

        return PostResource::collection($posts);
    }

    public function store(CreatePostRequest $request)
    {
        $post = $this->postService->create($request->all());

        return PostResource::make($post);
    }

    public function show($id)
    {
        return PostResource::make($this->postService->getById($id));
    }

    public function edit(EditPostRequest $request, $id)
    {
        return PostResource::make($this->postService->getById($id));
    }

    public function update(UpdatePostRequest $request, $id)
    {
        return PostResource::make($this->postService->update($id, $request->all()));
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PostController extends Controller
{

    public function index()
    {
        return view('post.index');
    }

    public function create(Request $request)
    {
        return view('post.create');
    }

    public function show($id)
    {
        return view('post.show', ['postId' => $id]);
    }

    public function edit(Request $request, $postId)
    {
        return view('post.update', ['postId' => $postId]);
    }

}

resources/views/post/create.blade.php
@extends('app')

@section('content')
    <div class="container">

        <h1 class="my-5 text-center">{{ __('Create news') }}</h1>

        @include('vue-templates.post.post-form')
        <post-form></post-form>

    </div>
@endsection

resources/views/post/index.blade.php
@extends('app')

@section('content')
    <div class="container">
            @include('vue-templates.post.posts-list')
            <posts-list></posts-list>
    </div><!--asd-->
@endsection

resources/views/post/news-form.blade.php
@include('partial.alert_errors')

<form
    action="{{ !empty($post) ? route('posts.update', $post) : route('posts.store') }}"
    method="POST"
    class="news-form"
>

    @csrf

    @isset($post)
        @method('PATCH')
    @endisset

    <input
        type="text"
        name="title"
        value="@isset($post){{ $post->title }}@endisset"
        class="news-form__input news-form__input--title"
    />

    <textarea
        name="content"
        class="news-form__input news-form__textarea tinyeditor"
        rows="20"
    >
        @isset($post){{ $post->content }}@endisset
    </textarea>

    <button type="submit" class="btn btn-primary news-form__action">{{ __('Save') }}</button>

</form>

resources/views/post/show.blade.php
@extends('app')

@section('content')

    @include('vue-templates.post.post-show')
    <post-show :post-id="{{ $postId }}"></post-show>

    @include('vue-templates.comment.comments-list')

@endsection

resources/views/post/update.blade.php
@extends('app')

@section('content')
    <div class="container">

        <h1 class="my-5 text-center">{{ __('Update news') }}</h1>

        @include('vue-templates.post.post-form')
        <post-form v-bind:post-id="{{ $postId }}"></post-form>

        {{--        @include('post.news-form')--}}

{{--        <form action="{{ route('posts.destroy', $post) }}" method="POST" class="text-right">--}}
{{--            @csrf--}}
{{--            @method('delete')--}}
{{--            <input--}}
{{--                type="submit"--}}
{{--                onclick="confirm('{{ __('The post will be deleted?') }}')"--}}
{{--                class="btn btn-danger"--}}
{{--                value="{{ __('Remove') }}"--}}
{{--            />--}}
{{--        </form>--}}
    </div>
@endsection