routes/web.php
<?php

use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use App\Mail\AdminReport;
use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function() {
    return redirect()->route('posts.index');
});


Route::resource('users', UserController::class);
Route::resource('posts', PostController::class);

Auth::routes();

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class Post extends Model
{
    use HasFactory;

    const PER_PAGE = 10;

    protected $fillable = ['title', 'content', 'user_id'];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class)->orderByDesc('id');
    }

    public function getDescriptionAttribute() {
        return Str::words(strip_tags($this->content), 25);
    }
}

app/Http/Controllers/Api/PostController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Post\CreatePostRequest;
use App\Http\Requests\Post\EditPostRequest;
use App\Http\Requests\Post\UpdatePostRequest;
use App\Http\Resources\PostResource;
use App\Services\Contracts\IPostService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{

    protected IPostService $postService;

    public function __construct(IPostService $postService)
    {
        $this->postService = $postService;
    }

    public function index()
    {
        $posts = $this->postService->getAll();

        return PostResource::collection($posts);
    }

    public function store(CreatePostRequest $request)
    {
        $post = $this->postService->create($request->all());

        return PostResource::make($post);
    }

    public function show($id)
    {
        return PostResource::make($this->postService->getById($id));
    }

    public function edit(EditPostRequest $request, $id)
    {
        return PostResource::make($this->postService->getById($id));
    }

    public function update(UpdatePostRequest $request, $id)
    {
        return PostResource::make($this->postService->update($id, $request->all()));
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PostController extends Controller
{

    public function index()
    {
        return view('post.index');
    }

    public function create(Request $request)
    {
        return view('post.create');
    }

    public function show($id)
    {
        return view('post.show', ['postId' => $id]);
    }

    public function edit(Request $request, $postId)
    {
        return view('post.update', ['postId' => $postId]);
    }

}

resources/views/vue-templates/post/post-form.blade.php
<script type="text/x-template" id="post-form-template">
    <form
        action="{{ !empty($postId) ? route('api.posts.update', $postId) : route('api.posts.store') }}"
        class="news-form"
        @submit.prevent="submitForm"
    >
        <span v-if="errors.credential" class="invalid-feedback d-block" role="alert">
            <strong>{# errors.credential #}</strong>
        </span>

        <input
            v-model="title"
            type="text"
            name="title"
            class="news-form__input news-form__input--title"
            :class="{'is-invalid': errors.title}"
        />
        <span v-if="errors.title" class="invalid-feedback" role="alert">
            <strong>{# errors.title[0] #}</strong>
        </span>

        <editor
            v-model="content"
            api-key="no-api-key"
            :init="{
                height: 500,
                menubar: false,
                plugins: [
                    'advlist autolink lists link image charmap print preview anchor',
                    'searchreplace visualblocks code fullscreen',
                    'insertdatetime media table paste code help wordcount'
                ],
                toolbar:
                    'undo redo | formatselect | bold italic backcolor | \
                    alignleft aligncenter alignright alignjustify | \
                    bullist numlist outdent indent | removeformat | help'
            }"
        />
        <span v-if="errors.content" class="invalid-feedback" role="alert">
            <strong>{# errors.content[0] #}</strong>
        </span>

        <button type="submit" class="btn btn-primary news-form__action">{{ __('Save') }}</button>

    </form>
</script>

resources/views/vue-templates/post/post-show.blade.php
<script type="text/x-template" id="posts-show-template">
    <div class="container">

        <div class="single-post" v-if="post">

            <h1 class="text-center mb-5 single-post__title">
                {# post.title #}
                <a v-if="post.url_edit" :href="post.url_edit" class="single-post__edit">
                    <i class="fas fa-pencil"></i>
                </a>
            </h1>

            <div class="d-flex justify-content-between mb-5 py-2 single-post__header">

                <div class="single-post__author">
                    {# post.user.name #}
                    <br>
                    {# post.user.email #}
                </div>

                <div class="single-post__date">
                    {# post.created_at #} {{ __('updated') }} ({# post.updated_at #})
                </div>

            </div>

            <div class="single-post__content" v-html="post.content"></div>

        </div>

        <comments-list></comments-list>
    </div>
</script>

resources/views/vue-templates/post/posts-list.blade.php
<script type="text/x-template" id="posts-list-template">
    <div>
        <div class="posts">

            <div v-for="post in posts" class="post">

                <div class="post__header">

                    <h2 class="post__title">
                        <a :href="post.url">
                            {# post.title #}
                        </a>
                    </h2>

                    <a v-if="post.url_edit" :href="post.url_edit" class="single-post__edit">
                        <i class="fas fa-pencil"></i>
                    </a>

                </div>

                <div class="post__body">
                    {# post.description #}
                </div>

                <div class="post__footer">
                    <div class="post__date">{# post.created_at #}</div>
                    <div class="post__author">
                        {# post.user.name #}
                        <br /><small>{# post.user.email #}</small>
                    </div>
                </div>

            </div>

        </div>
        <div class="row">
            <nav aria-label="Page navigation example">
                <ul class="pagination d-flex justify-content-center">
                    <li
                        v-for="link of pagination.links"
                        :class="{'page-item': true, 'disabled': !link.url, 'active': link.active}"
                    >
                        <a
                            class="page-link"
                            :href="link.url ? link.url : '#'"
                            v-html="link.label"
                            @click.prevent="listenSelectPagination(link.label)"
                        ></a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</script>