routes/web.php
<?php

use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use App\Mail\AdminReport;
use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function() {
    return redirect()->route('posts.index');
});


Route::resource('users', UserController::class);
Route::resource('posts', PostController::class);

Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    const PER_PAGE = 5;

    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new \App\Notifications\MailResetPasswordNotification($token));
    }

    public function profile(): HasOne
    {
        return $this->hasOne(Profile::class);
    }

    public function posts(): HasMany
    {
        return $this->hasMany(Post::class);
    }

    public function comment(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

    public function skills(): BelongsToMany
    {
        return $this->belongsToMany(Skill::class);
    }

    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(Role::class);
    }

    public function getTokenNameAttribute() {
        return $this->name . ': ' . $this->email;
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\RemoveUserAvatarRequest;
use App\Http\Requests\User\SaveUserAvatarRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\Http\Resources\UserResource;
use App\Models\User;
use App\Services\Contracts\IUserService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{

    protected IUserService $userService;

    public function __construct(IUserService $userService)
    {
        $this->userService = $userService;
    }

    public function index(Request $request)
    {
        $users = $this->userService->getAll($request->all());

        return UserResource::collection($users);
    }

    public function update(UpdateUserRequest $request, User $user)
    {
        return UserResource::make($this->userService->update($request->all(), $user));
    }

    public function saveAvatar(SaveUserAvatarRequest $request)
    {
        $this->userService->saveAvatar($request->all());
    }

    public function removeAvatar(RemoveUserAvatarRequest $request, $userId)
    {
        $this->userService->removeAvatar($userId);
    }

    public function getCurrentUser()
    {
        return UserResource::make($this->userService->getUser(Auth::id()));
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

class UserController extends Controller
{
    public function index()
    {
        return view('user.index');
    }
}

resources/views/user/create.blade.php
@extends('app')

@section('content')
    <div class="container" style="display:flex; align-items:center; justify-content:center; flex-direction: column; min-height: 90vh">

        @include('partial.alert_errors')

        <form method="POST" action="{{ route('users.store') }}" class="form" style="max-width: 600px;margin:auto; width: 100%;">
            @csrf
            <h1 class="text-center">Create user</h1>
            <div class="mb-3">
                <label for="inputName" class="form-label">Name</label>
                <input type="text" class="form-control" id="inputName"  name="name" value="{{old('name')}}">
            </div>
            <div class="mb-3">
                <label for="inputEmail" class="form-label">Email address</label>
                <input type="email" class="form-control" id="inputEmail" name="email" value="{{old('email')}}">
            </div>
            <div class="mb-3">
                <label for="inputPassword" class="form-label">Password</label>
                <input type="password" class="form-control" id="inputPassword" name="password" value="{{old('password')}}">
            </div>
            <div class="mb-3">
                <label for="inputPassword2" class="form-label">Confirm password</label>
                <input type="password" class="form-control" id="inputPassword2" name="password_confirmation" value="{{old('password_confirmation')}}">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

@endsection

resources/views/user/index.blade.php
@extends('app')

@section('content')
    <portfolio-list></portfolio-list>
    @include('vue-templates/portfolio-list')
@endsection

resources/views/user/show.blade.php
@extends('app')

@section('content')

    <div class="container" style="display:flex; align-items:center; justify-content:center; flex-direction: column; min-height: 90vh">
        <h1><a href="{{route('users.edit', $user)}}">{{$user->name}}</a></h1>
        <h2>{{$user->email}}</h2>

        <ul class="w-50 mt-5 list-group">
            <li class="list-group-item">Education: {{$user->profile->education}}</li>
            <li class="list-group-item">Experience: {{$user->profile->experience}}</li>
        </ul>
    </div>

@endsection

resources/views/user/update.blade.php
@extends('app')

@section('content')
    <div class="container" style="display:flex; align-items:center; justify-content:center; flex-direction: column; min-height: 90vh">

        @include('partial.alert_errors')

        <form method="POST" action="{{ route('users.update', $user) }}" class="form" style="max-width: 900px;margin:auto;width: 100%;">
            @csrf
            @method('PUT')
            <h1 class="text-center">Edit profile</h1>
            <div class="row">
                <div class="col-9">
                    <div class="mb-3">
                        <label for="inputName" class="form-label">Name</label>
                        <input
                            type="text"
                            class="form-control"
                            id="inputName"
                            name="user[name]"
                            value="{{$user->name ?? old('user.name')}}"
                        />
                    </div>
                    <div class="mb-3">
                        <label for="inputEmail" class="form-label">Email address</label>
                        <input
                            type="email"
                            class="form-control"
                            id="inputEmail"
                            name="user[email]"
                            value="{{$user->email ?? old('user.email')}}"
                        />
                    </div>

                    <div class="mb-3">
                        <label for="education" class="form-label">Education</label>
                        <select name="profile[education_id]" id="education" class="form-select">
                            @foreach($educations as $education)
                                <option
                                    value="{{ $education->id }}"
                                    @if($user->profile->education->id === $education->id) selected @endif>
                                    {{ $education->title }}
                                </option>
                            @endforeach
                        </select>
                    </div>

                    <div class="mb-3">
                        <label for="experience" class="form-label">Experience</label>
                        <input
                            type="text"
                            class="form-control"
                            id="education"
                            name="profile[experience]"
                            value="{{$user->profile ? $user->profile->experience : old('profile.experience')}}"
                        />
                    </div>

                    @if(count($roles))
                        <label class="form-label">Roles</label>
                        <div class="">
                            @foreach($roles as $role)
                                <div class="col form-check">
                                    <label for="role-{{ $role->slug }}" class="form-check-label">{{ $role->title }}</label>
                                    @if(\App\Facades\CheckUser::hasRole(['admin']))
                                        <input
                                            type="checkbox"
                                            class="form-check-input"
                                            id="role-{{ $role->slug }}"
                                            name="roles[]"
                                            value="{{ $role->id }}"
                                            {{ \App\Facades\CheckUser::hasRole([$role->slug], $user) ? 'checked' : '' }}
                                        />
                                    @endif
                                </div>
                            @endforeach
                        </div>
                    @endif


                    <hr class="mt-5 mb-5">

                    <div class="mb-3">
                        <label for="inputPassword" class="form-label">Password</label>
                        <input
                            type="password"
                            class="form-control"
                            id="inputPassword"
                            name="user[password]"
                            value=""
                        />
                    </div>
                    <div class="">
                        <label for="inputPassword2" class="form-label">Confirm password</label>
                        <input
                            type="password"
                            class="form-control"
                            id="inputPassword2"
                            name="user[password_confirmation]"
                            value=""
                        />
                    </div>
                </div>
                <div class="col-3">
                    <select name="skills[]" class="form-select h-100" multiple>
                        @foreach($skills as $skill)
                            <option
                                value="{{$skill->id}}"
                                {{in_array($skill->id, $user->skills->pluck('id')->toArray()) ? 'selected' : ''}}
                            >
                                {{$skill->title}}
                            </option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="mt-3 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
                <span id="userRemove" class="btn btn-danger ml-5">Remove</span>
            </div>
        </form>
        <script>
            window.addEventListener('load', function (){

                document.addEventListener('click', function (e){
                    const removeBtn = e.target.closest('#userRemove');
                    if(removeBtn) {
                        if(window.confirm('Удалить {{$user->name}}?')) {

                            const xhr = new XMLHttpRequest();
                            const data = new FormData();
                            data.append('_token', '{{csrf_token()}}')
                            data.append('_method', 'DELETE')
                            xhr.open("DELETE", '{{route('users.destroy', $user)}}');

                            xhr.setRequestHeader("X-CSRF-TOKEN", "{{csrf_token()}}");

                            xhr.onreadystatechange = function () {
                                if (xhr.readyState === 4 && xhr.status === 200) {
                                    document.location.href = xhr.responseText;
                                }
                            };

                            xhr.send(data);
                        }
                    }
                });
            });
        </script>
    </div>
@endsection